### ISSUE TITLE
support for prepublish scripts

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#278]
Both modules and targets should be able to specify scripts that will be run by `yt publish`. These could add/verify license headers, or preprocess/generate/precompile resource files.

**Comment by autopulated** [comment]
@pjbakker @mpg Would this work for your relicensing needs?

**Comment by pjbakker** [comment]
Which needs specifically are you referring to?)

mbed TLS will be (after beta) licensed as Apache in source (just like everything else I hope).
We will need to publish a GPL package, but that won't be Yotta, I assume.

It could help for all components in general, as we will need the partner licensed version in the private registry. The question then is: Does it make sense to add those to the manifest, as it should only occur for the private registry, not our regular publications to the public registry.

Maybe I'm misunderstanding your purpose/goal here.

**Comment by mpg** [comment]
The current plan is to have our own script to generate the yotta module anyway, so as far as I'm concerned it makes no big difference if relicensing happens when we generate the module or when we publish it.

(Besides, unless I'm mistaken the need to relicense should be temporary, once we've moved to Apache everyone will use the same license, right? @pjbakker?)

**Comment by autopulated** [comment]
ok, thanks
