### ISSUE TITLE
yotta modules allow case sensitivity

### ISSUE THREAD

**Issue by sg-** [ARMmbed/yotta#502]
Forcing yotta modules to use lowercase letters is a PITA. This means that all class names would need to be lowercase to match the module name and namespace name or it it unintuitive to guess at the camelcase assuming we use the same coding guidelines from mbed v2. Maybe we've changed the coding guidelines but if not this will be a problem.

**Comment by autopulated** [comment]
yotta modules are lowercase-only to prevent confusingly similar names: this isn't going to change!

That doesn't mean you have to use lowercase class or variable names. Because you know that there aren't case-only variants of your name, you're free to use any case you wish for your naming. yotta does not care about your case conventions. I don't have a link to the mbed OS coding conventions, but the yotta module tutorial includes some as an example: http://yottadocs.mbed.com/tutorial/tutorial.html
