### ISSUE TITLE
Yotta uses tagged version instead of branch specified in top level module.json

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/yotta#602]
I have test application that needs to fetch master branches of some repositories instead of tagged releases.

I define the branch in *module.json* like this:
~~~
"sal-stack-nanostack": "ARMmbed/sal-stack-nanostack-private#master"
~~~

However, the test run randomly picks up either tagger version from there, or the branch.

When things work as expected I get following:
~~~
09:56:42 warning: Using head of "master" branch for "sal-stack-nanostack", not a tagged version
09:56:42 info: download sal-stack-nanostack@master from GitHub ARMmbed/sal-stack-nanostack-private
~~~

When it does not work, I get this:
~~~
15:36:25 info: get versions for sal-stack-nanostack
15:36:26 info: download sal-stack-nanostack@v3.0.5 from GitHub ARMmbed/sal-stack-nanostack-private
~~~

Think the branch name on top level application should be mandating the Yotta so that it then skips the version tags of that repo. This is much needed feature to allow CI machines to test our software BEFORE creating the release tags of those modules.

**Comment by autopulated** [comment]
Does the behaviour change randomly if you repeat the same build after removing `./yotta_modules` (I suspect not?)

This is almost certainly caused by multiple modules in your tree depending on the module in question. The version specification that will be used is the first that's encountered. So whether the specified branch is used, or the latest server-tagged version (the no-branch-specified behaviour) will depend on which dependency specification is encountered first.

This behaviour won't change without a complete re-visit of yotta's dependency resolution algorithm (see #537), sorry!

If you want to build with an exact version of your dependency:

 * first consider whether this is really the appropriate thing to be doing. When you release a new version of your module, your users will get it with the **current** version of its dependencies, not the git version: so that is the appropriate version to be testing with.
 * If you really want to do this, then have your CI system either use `yotta link` to link in the exact version that you want, or create its own symlink from yotta_modules to the exact version that should be used.
